### PR TITLE
Hide parcel terminal if country iso code is not 'LT'

### PR DESCRIPTION
**Pull request by gadnis**
As far as I know, parcel terminals available only in Lithuania, I could not find the solution to hide this carrier for other countries, so maybe this is the solution.

If you think this is the approach, you are welcome 😁

### CODE REVIEW

**Comment by aidzas** [comment]
Hello,
Parcel terminals are available in LT, LV and EE

**Comment by gadnis** [comment]
Is this ok?

**Comment by LithMage** [comment]
Hi, in prestashop limiting to specific countries is done through carrier settings, assigning particular geozones (its possible to create geozone of just Baltic states for example). Same is with pricing, and pricing ranges - that is why module itself does not have separate settings for country and price settings.

**Comment by gadnis** [comment]
@LithMage I didn't do that because there is many posts that it is not working as it should, prestashop has some bugs. But OK, I'll try to do it as you described, maybe it is working properly in latest PS version.

**Comment by gadnis** [comment]
So I created separate zones for each baltic country and as @LithMage described I applied different delivery prices for each zone. PrestaShop works without any bug (version 1.7.6.5).

So this pull request can be closed. Thank you 😁

**Pull request closed without merging**
